// Code generated by finalunit dev, visit us at https://finalunit.com
package complex

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/suite"
)

type ComplexSuite struct {
	suite.Suite
}

type MPQhy struct {
}

func (s *MPQhy) Do() (*Response, error) {
	ehuPucpkfI := Response{Message: "Roareroasis"}
	ehuPu := &ehuPucpkfI
	dYLJj := func() error {
		return nil
	}()
	return ehuPu, dYLJj
}

func (s *ComplexSuite) TestWorkerSomeFunc0() {

	aoOHbfMInY := Worker{Client: &MPQhy{}}
	aoOHb := &aoOHbfMInY
	rlLZP := []int{99, 55, 46, 25}

	kOZbX, mzhJN := aoOHb.SomeFunc(rlLZP)

	s.EqualValues(string(`Roareroasis, [99 55 46 25]`), kOZbX)
	s.NoError(mzhJN)

	_ = kOZbX
	_ = mzhJN

}

type WRJGX struct {
}

func (s *WRJGX) Do() (*Response, error) {
	wpYUJPlFpl := Response{Message: "Pigquark"}
	wpYUJ := &wpYUJPlFpl
	ifhrv := func() error {
		return fmt.Errorf("very error")
	}()
	return wpYUJ, ifhrv
}

func (s *ComplexSuite) TestWorkerSomeFunc1() {

	rnKVUWQFgN := Worker{Client: &WRJGX{}}
	rnKVU := &rnKVUWQFgN
	dsFmw := []int{26, -91, 60, 26, -19}

	wUNeQ, oqkff := rnKVU.SomeFunc(dsFmw)

	s.EqualValues(string(``), wUNeQ)
	s.Error(oqkff)

	_ = wUNeQ
	_ = oqkff

}

type HHTVo struct {
}

func (s *HHTVo) Do() (*Response, error) {
	gUVukLZtqu := Response{Message: "Houndbow"}
	gUVuk := &gUVukLZtqu
	vESoj := func() error {
		return nil
	}()
	return gUVuk, vESoj
}

func (s *ComplexSuite) TestWorkerSomeFunc2() {

	cPxMqWsdyV := Worker{Client: &HHTVo{}}
	cPxMq := &cPxMqWsdyV
	dBkcm := []int{56, 90, 14, -53, 17, 89, -42, 27}

	jOzUV, jIcYP := cPxMq.SomeFunc(dBkcm)

	s.EqualValues(string(`Houndbow, [56 90 14 -53 17 89 -42 27]`), jOzUV)
	s.NoError(jIcYP)

	_ = jOzUV
	_ = jIcYP

}

type YGsec struct {
}

func (s *YGsec) Do() (*Response, error) {
	tgzoeXMGMz := Response{Message: "Salmonmud"}
	tgzoe := &tgzoeXMGMz
	nsBdM := func() error {
		return fmt.Errorf("very error")
	}()
	return tgzoe, nsBdM
}

func (s *ComplexSuite) TestWorkerSomeFunc3() {

	xzHIAqtiwS := Worker{Client: &YGsec{}}
	xzHIA := &xzHIAqtiwS
	rrKAD := []int{46, 88, -23, -98, -52}

	elogL, yyjMW := xzHIA.SomeFunc(rrKAD)

	s.EqualValues(string(``), elogL)
	s.Error(yyjMW)

	_ = elogL
	_ = yyjMW

}

type WZKlV struct {
}

func (s *WZKlV) Do() (*Response, error) {
	ePJDgtdwtK := Response{Message: "Foebush"}
	ePJDg := &ePJDgtdwtK
	sujtw := func() error {
		return fmt.Errorf("very error")
	}()
	return ePJDg, sujtw
}

func (s *ComplexSuite) TestWorkerSomeFunc4() {

	mTOjaCYSGn := Worker{Client: &WZKlV{}}
	mTOja := &mTOjaCYSGn
	glPDY := []int{4}

	hedXS, nXEzm := mTOja.SomeFunc(glPDY)

	s.EqualValues(string(``), hedXS)
	s.Error(nXEzm)

	_ = hedXS
	_ = nXEzm

}

type NfGnZ struct {
}

func (s *NfGnZ) Do() (*Response, error) {
	uhzrnNvJuL := Response{Message: "Haircrazy"}
	uhzrn := &uhzrnNvJuL
	pxeor := func() error {
		return fmt.Errorf("very error")
	}()
	return uhzrn, pxeor
}

func (s *ComplexSuite) TestWorkerSomeFunc5() {

	acthCABjFJ := Worker{Client: &NfGnZ{}}
	acthC := &acthCABjFJ
	zAjyo := []int{-44, 76}

	nIegS, rFKCD := acthC.SomeFunc(zAjyo)

	s.EqualValues(string(``), nIegS)
	s.Error(rFKCD)

	_ = nIegS
	_ = rFKCD

}

type XEscF struct {
}

func (s *XEscF) Do() (*Response, error) {
	gMZScbablq := Response{Message: "Hooflunar"}
	gMZSc := &gMZScbablq
	wwgUm := func() error {
		return fmt.Errorf("very error")
	}()
	return gMZSc, wwgUm
}

func (s *ComplexSuite) TestWorkerSomeFunc6() {

	dkYnuMerwj := Worker{Client: &XEscF{}}
	dkYnu := &dkYnuMerwj
	ncbVy := []int{-75, 74, -7, 90, -31, -68, 42, 50, 44}

	lapTi, ggRFU := dkYnu.SomeFunc(ncbVy)

	s.EqualValues(string(``), lapTi)
	s.Error(ggRFU)

	_ = lapTi
	_ = ggRFU

}

type LHSxb struct {
}

func (s *LHSxb) Do() (*Response, error) {
	zBkzgsbnoZ := Response{Message: "Bonepollen"}
	zBkzg := &zBkzgsbnoZ
	uEYXA := func() error {
		return fmt.Errorf("very error")
	}()
	return zBkzg, uEYXA
}

func (s *ComplexSuite) TestWorkerSomeFunc7() {

	azirqwLFSZ := Worker{Client: &LHSxb{}}
	azirq := &azirqwLFSZ
	xORKp := []int{44, -72, 15, -62, 76, 31, 89, -26, 40}

	vFceE, xZUPv := azirq.SomeFunc(xORKp)

	s.EqualValues(string(``), vFceE)
	s.Error(xZUPv)

	_ = vFceE
	_ = xZUPv

}

type UAAEL struct {
}

func (s *UAAEL) Do() (*Response, error) {
	rcCpUZBBVU := Response{Message: "Healergray"}
	rcCpU := &rcCpUZBBVU
	gdWPe := func() error {
		return fmt.Errorf("very error")
	}()
	return rcCpU, gdWPe
}

func (s *ComplexSuite) TestWorkerSomeFunc8() {

	iPmcMbLbWQ := Worker{Client: &UAAEL{}}
	iPmcM := &iPmcMbLbWQ
	dsGVg := []int{94, 6, 3}

	kPtkw, oajXD := iPmcM.SomeFunc(dsGVg)

	s.EqualValues(string(``), kPtkw)
	s.Error(oajXD)

	_ = kPtkw
	_ = oajXD

}

type EUgYN struct {
}

func (s *EUgYN) Do() (*Response, error) {
	nqZfuNmBSg := Response{Message: "Healerbronze"}
	nqZfu := &nqZfuNmBSg
	ylEyd := func() error {
		return nil
	}()
	return nqZfu, ylEyd
}

func (s *ComplexSuite) TestWorkerSomeFunc9() {

	htUGYihwFl := Worker{Client: &EUgYN{}}
	htUGY := &htUGYihwFl
	gqubQ := []int{-26, 83, 19, 4, 89, -31, -48}

	gVDIc, lvqxk := htUGY.SomeFunc(gqubQ)

	s.EqualValues(string(`Healerbronze, [-26 83 19 4 89 -31 -48]`), gVDIc)
	s.NoError(lvqxk)

	_ = gVDIc
	_ = lvqxk

}

func TestComplexSuite(t *testing.T) {
	suite.Run(t, new(ComplexSuite))
}
