// Code generated by finalunit dev, visit us at https://github.com/wimspaargaren/final-unit
package basic

import (
	"testing"

	"github.com/stretchr/testify/suite"
)

type BasicSuite struct {
	suite.Suite
}

func (s *BasicSuite) TestFooBar0() {
	sNCEIXbgwF := Foo{}
	sNCEI := &sNCEIXbgwF
	ajNkf := -50

	krDNh := sNCEI.Bar(ajNkf)

	s.EqualValues(string(`x is a negative integer`), krDNh)

	_ = krDNh
}

func (s *BasicSuite) TestFooBar1() {
	ziLZMiGhUL := Foo{}
	ziLZM := &ziLZMiGhUL
	rtvmX := 35

	kgQMY := ziLZM.Bar(rtvmX)

	s.EqualValues(string(`x between 30 and 50`), kgQMY)

	_ = kgQMY
}

func (s *BasicSuite) TestFooBar2() {
	rGXWUJGUbj := Foo{}
	rGXWU := &rGXWUJGUbj
	zeLdt := -22

	feRXC := rGXWU.Bar(zeLdt)

	s.EqualValues(string(`x is a negative integer`), feRXC)

	_ = feRXC
}

func (s *BasicSuite) TestFooBar3() {
	zsbosljAei := Foo{}
	zsbos := &zsbosljAei
	sosAQ := 72

	fdDwm := zsbos.Bar(sosAQ)

	s.EqualValues(string(`x not recognized: 72`), fdDwm)

	_ = fdDwm
}

func (s *BasicSuite) TestFooBar4() {
	kAlMmAcgbP := Foo{}
	kAlMm := &kAlMmAcgbP
	kJKHc := -12

	wNzHG := kAlMm.Bar(kJKHc)

	s.EqualValues(string(`x is a negative integer`), wNzHG)

	_ = wNzHG
}

func (s *BasicSuite) TestFooBar5() {
	gJpOxaEeGT := Foo{}
	gJpOx := &gJpOxaEeGT
	dkWDP := -67

	tWyMy := gJpOx.Bar(dkWDP)

	s.EqualValues(string(`x is a negative integer`), tWyMy)

	_ = tWyMy
}

func (s *BasicSuite) TestFooBar6() {
	hSAJJjUiuN := Foo{}
	hSAJJ := &hSAJJjUiuN
	gDcQh := -6

	kFQsA := hSAJJ.Bar(gDcQh)

	s.EqualValues(string(`x is a negative integer`), kFQsA)

	_ = kFQsA
}

func (s *BasicSuite) TestFooBar7() {
	jvcmjNnsqo := Foo{}
	jvcmj := &jvcmjNnsqo
	mIUgm := -85

	nFWbN := jvcmj.Bar(mIUgm)

	s.EqualValues(string(`x is a negative integer`), nFWbN)

	_ = nFWbN
}

func (s *BasicSuite) TestFooBar8() {
	mPrSGyVGxA := Foo{}
	mPrSG := &mPrSGyVGxA
	qXkSX := 62

	nwomu := mPrSG.Bar(qXkSX)

	s.EqualValues(string(`x not recognized: 62`), nwomu)

	_ = nwomu
}

func (s *BasicSuite) TestFooBar9() {
	kOyqDGOTmc := Foo{}
	kOyqD := &kOyqDGOTmc
	sMsyX := 11

	btdqz := kOyqD.Bar(sMsyX)

	s.EqualValues(string(`x between 10 and 20`), btdqz)

	_ = btdqz
}

func TestBasicSuite(t *testing.T) {
	suite.Run(t, new(BasicSuite))
}
